### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by e3duardo** [pez2001/razer_chroma_drivers#100]
Thanks by doing this. My BlackWidow is now working on Debian.
I managed to install on Debian 8.3 installing these dependencies:

`$ apt-get install python3-dbus python3-dbus.mainloop.qt`
`$ apt-get install gir1.2-webkit-3.0`

**Comment by terrycain** [comment]
No problem. Cheers for the dependencies, I'm currently packaging it for Ubuntu 14.04 onwards, and will go and add Debian packages soon after, what Debian version you using?

**Comment by terrycain** [comment]
@e3duardo are you sure it needs python3-dbus.mainloop.qt, as it uses glib's main loop not qt's?
