### ISSUE TITLE
Dependency list in README is missing gir1.2-webkit-3.0

### ISSUE THREAD

**Issue by storborg** [pez2001/razer_chroma_drivers#110]
On Ubuntu 16.04, the ``gir1.2-webkit-3.0`` package is required for the GUI apps (chroma controller app and the tray applet), but it isn't mentioned in the docs. I think this is also the case on other Ubuntu versions and Debian jessie/sid, but haven't verified that.

**Comment by terrycain** [comment]
Done, when we package and finalise all of the code for version 1 I'll make a proper page to list dependencies.
