### ISSUE TITLE
Load specific profile at startup?

### ISSUE THREAD

**Issue by dbb** [pez2001/razer_chroma_drivers#113]
Is it possible to specify a profile to be loaded when the daemon starts?

I checked the commands' `-h` output, the README, and the issues page but could not find this.

As a side note, I'm not using the tray applet (it doesn't work, and I'd rather just stick with the daemon + controller).

**Comment by lah7** [comment]
I presume you are referring to the profiles produced by the Chroma GUI App. Only the tray applet can load one automatically at start-up (options available in GUI's preferences).

You can write your own Python script and load that at start up:

    #!/usr/bin/env python3
    import razer.daemon_dbus
    import razer.profiles
    daemon = razer.daemon_dbus.DaemonInterface()
    profile = razer.profiles.ChromaProfiles(daemon)
    profile.activate_profile_from_file("<Profile filename>")
