### ISSUE TITLE
Razer Abyssus 2014 support

### ISSUE THREAD

**Issue by claell** [pez2001/razer_chroma_drivers#114]
I post this as an issue to express my demand for support of the Razer Abyssus 2014. Maybe it can get supported one day.

**Comment by terrycain** [comment]
Are you willing to help us get support? As it's hard to code for it without owning one.

**Comment by claell** [comment]
Yes, I could help with it, of course.

**Comment by terrycain** [comment]
OK, well what I need is packet captures. Read this issue #82 from about commend 17 onwards. There is a link to the wiki page there and some examples of what you should be getting. [Wiki Page](https://github.com/pez2001/razer_chroma_drivers/wiki/Reverse-Engineering-USB-Protocol)

**Comment by claell** [comment]
Alright. I will do my best :)

**Comment by terrycain** [comment]
That's all we ask ;). I have decided to go through the wiki page and finally add the images it should of had ages ago.

**Comment by claell** [comment]
I guess a virtual box is essential to capture things, right?

**Comment by terrycain** [comment]
Yep, or vmware but virtualbox is easier in my opinion

**Comment by terrycain** [comment]
And installing windows in a VM

**Comment by claell** [comment]
Alright.

**Comment by terrycain** [comment]
Its a bit involved but is all that can be done, short of you sending me said device that is lol.

**Comment by claell** [comment]
I don't understand the sentence completely :)

**Comment by terrycain** [comment]
I'm just saying its a lot of work just to get a mouse working :wink:. The only other thing you could do is mail me your mouse and I do all the hard work.

**Comment by claell** [comment]
Ah, alright. But I guess it is rather easy compared with other devices, as it does not have many functions. I am currently downloading a Windows image.

**Comment by terrycain** [comment]
Well it should take near no effort once I have some packet captures as my
Mamba Chroma should have all the features and more so shouldn't even have
to code much.

Once you have the windows installed, install synapse. Once synapse is
installed pass the USB device to the VM (there is some discussion in that
bug report I sent you about that). Synapse should recognise the mouse and
you "should" be able to configure it. If you get this far, take screenshots
of all the synapse options, zip them up and send them to me.

As your giving the VM full control over your mouse, the mouse wont work on
linux whilst the VM is on, so plug in a spare mouse and use that whilst
capturing packets.

**Comment by claell** [comment]
Alright. Good that I have a spare mouse

**Comment by claell** [comment]
Installed synapse now. Will continue later when I have time again.

**Comment by claell** [comment]
After installing the extension pack from Virtualbox I managed to pass the mouse through to Windows. It seems it got recognized. Shell I upload the screenshot zip here?

**Comment by terrycain** [comment]
yeah here is fine

**Comment by claell** [comment]
Ok. It just installed the driver.

**Comment by claell** [comment]
Alright. Took screenshots from every page of the driver I could access.
[Razer Abyssus 2014.zip](https://github.com/pez2001/razer_chroma_drivers/files/230370/Razer.Abyssus.2014.zip)

**Comment by terrycain** [comment]
Ok whats the output from `lsusb`

**Comment by terrycain** [comment]
Ok not being able to speak or read german this is what I think we've got.

* DPI Slider
* Checkbox to toggle X and Y DPI
* Possibly an acceleration slider
* frequency dropdown list in Hz
* Toggle for the light on the mouse

Am I right?

**Comment by claell** [comment]
Correct (Checkbox to toggle X and Y DPI is translated: activate sensibility for x- and y- axis, don't know, whether this is the same).

**Comment by terrycain** [comment]
OK now you need to run `sudo modprobe usbmon` then load up wireshark as root

also output of `lsusb`

**Comment by terrycain** [comment]
Follow the rest of the Wiki to result in some packet captures

**Comment by claell** [comment]
relevant output of lsusb: Bus 001 Device 003: ID 1532:0042 Razer USA, Ltd

**Comment by claell** [comment]
Started wireshark and selected all usb entries. Applied filter usb.bus_id == 1 && usb.device_address == 3

**Comment by claell** [comment]
What do I need to do now? Just send some commands to the mouse from synapse and log with wireshark? Do I need to protocoll which commands I sent at which time?

**Comment by terrycain** [comment]
Cool now for each option I listed toggle or slide the slider a few times (preferably make a note of what values you slide/toggled to). A separate capture per option would be good.

**Comment by claell** [comment]
Ok.

**Comment by terrycain** [comment]
Do one feature at a time, for example the logo on the mouse a packet capture should contain it being toggled on and off like 3 times.

For the sliders slide it from minimum to maximum 3 times.

**Comment by claell** [comment]
Will do.

**Comment by claell** [comment]
I have collected all data. Just need to find out, how to send them to you. I think I will upload them to a file hoster and post the link here.

**Comment by terrycain** [comment]
If you zip them you can just drag the zip into the comment box and GitHub will upload it

**Comment by claell** [comment]
Problem is a single file is larger than 15 MB sometimes :)

**Comment by claell** [comment]
Complete zip file is around 70MB.

**Comment by terrycain** [comment]
Ahh I didnt know if there was a limit. If you have google drive that isnt a bad place to put them

**Comment by claell** [comment]
I upload them to jumpshare as I don't want to mess up Google drive. Should be fine as well.

**Comment by claell** [comment]
BTW: There is also an option in the software to automatically deactivate lighting when screen turns off. Is this a driver specific or only software feature?

**Comment by terrycain** [comment]
That's part of the Synapse software

**Comment by claell** [comment]
Ok

**Comment by claell** [comment]
Here is the link: http://jmp.sh/bvn13aQ

I did a capture of just ticking the X Y checkbox, probably not needed. Also note that I first slided the Y slider and after that the X slider.

**Comment by claell** [comment]
Also with "frequeny checkbox" (filename) I mean "frequency dropdown".

**Comment by terrycain** [comment]
Ok I've got the logo and the refresh interval drop down. But the other captures didn't contain anything useful. The filter `(frame.len == 154) && (usb.endpoint_number == 0x00)` also will limit the output alot to exactly whats needed.

Can you redo all of them but the logo. and for the refresh rate ones can you note down what option you selected as I have the refresh rate but I dont know what lines refer to what option.

**Comment by terrycain** [comment]
Im specifically after the packets of 154 bytes of length.

**Comment by claell** [comment]
In the dropdown menu I started with the lowest rate (I think 125) and went up to the highest.

I will redo all captures with the new filter.

**Comment by claell** [comment]
Dropdown List: 
[Framerate 125-500-1000.pcapng.zip](https://github.com/pez2001/razer_chroma_drivers/files/230599/Framerate.125-500-1000.pcapng.zip)

I didn't get data for the sliders with your filter applied.

**Comment by claell** [comment]
I also tried usb.bus_id == 1 && usb.device_address == 3 && (usb.endpoint_number == 0x00)
and usb.bus_id == 1 && usb.device_address == 3 && (frame.len == 154) as filter but without any data.

**Comment by claell** [comment]
Here is a short sample of me recording a short random change of clicking on the DPI slider. Maybe you can identify some characteristic patterns leading to a good filter.
[DPI random change.pcapng.zip](https://github.com/pez2001/razer_chroma_drivers/files/230602/DPI.random.change.pcapng.zip)

**Comment by claell** [comment]
Tomorrow I can continue testing.

**Comment by terrycain** [comment]
Nothing in the DPI. Got the Refresh Rate done though. Try the DPI again without any filters, it will collect a mass of data but it might get something. I am starting to think that you mouse might not actually change DPI in hardware but it will take more packet captures to prove that.

**Comment by claell** [comment]
I also thought that it might only change it in the software, but I think I noticed a change of behaviour when switching back to the Linux system.

I will collect some data without a filter.

**Comment by claell** [comment]
After some testing you might be right that it is not applied in the hardware. It seems to have no effect when changing to Linux. Although I thought that DPI has increased after connecting to synapse for the first time and switching to Linux after that.

**Comment by claell** [comment]
Here is a capture without filters. I also closed the synapse software at the end. After closing it the applied settings persist. However when making the mouse available to Linux and then again to the VM the settings seem to be reset until I restart the synapse software.
[DPI changed and closed synapse.pcapng.zip](https://github.com/pez2001/razer_chroma_drivers/files/231256/DPI.changed.and.closed.synapse.pcapng.zip)

**Comment by terrycain** [comment]
Nothing again well there was a logo change and refresh rate change but that's it. From what you've said it could quite possibly be that synapse is just changing the windows mouse speed, or doing something clever in software.

The driver is currently undergoing a massive overhaul, ill add this to it at some point soonish.

**Comment by claell** [comment]
Strange. I did not change the logo nor the refresh rate. I just changed DPI and closed the software after it.

I also opened the Windows Mouse speed window and it does not appear to be changed by the software. So it is probably some hidden thing, if it is only software specific.

**Comment by claell** [comment]
I guess it is pretty clear that the changes are only software changes, right?

**Comment by claell** [comment]
So I just think that I noticed a DPI change on Linux: There is a difference when deactivating pass through with synapse open and synapse closed before. On the Linux system is a change in DPI for me, so a hint that there is something stored on the mouse probably.

**Comment by terrycain** [comment]
I know synapse sets all settings to the last settings it knows which is probably why it set the refresh rate and the logo. There could be, I've emailed my razer contact to see if they are willing to shed any light on the issue

**Comment by claell** [comment]
Ok, this is probably the reason.

Hopefully your contact can help.

**Comment by terrycain** [comment]
I shall say for now this issue is closed. I have the codes for refresh rate but want to investigate that further + am talking to razer about mice in general too.

As for the controller app, well I've got alot of things I plan to do before updating that to work with more devices.

**Comment by claell** [comment]
Thanks for the help and support for the device.

Any news from your contact, whether setting DPI and acceleration is supported or only software specific?

**Comment by terrycain** [comment]
No news yet, they have only discussed keyboards with me so far, am trying to move the topic onto mice but the 7hour time difference makes the conversation take days. Will let you know if I ever hear anything relating to DPI

**Comment by claell** [comment]
Alright
