### ISSUE TITLE
Installation tutorial

### ISSUE THREAD

**Issue by claell** [pez2001/razer_chroma_drivers#119]
On github there is a wrong path in step one of the installation tutorial:

Download the source code:

```
git clone --depth=1 https://github.com/pez2001/razer_blackwidow_chroma_driver.git
cd razer_blackwidow_chroma_drive
```

Also I saw that there is a different git link on http://pez2001.github.io/razer_chroma_drivers/

`git clone --depth=1 https://github.com/pez2001/razer_chroma_drivers.git`

**Comment by terrycain** [comment]
Ahh good spot, we had a different repo name a while ago. Shall go and fix now.

**Comment by claell** [comment]
There is still the wrong path (missing s):

`cd razer_blackwidow_chroma_drive`

**Comment by terrycain** [comment]
Oh yeah, good shout. Fixed

**Comment by claell** [comment]
I meant this section on https://github.com/pez2001/razer_chroma_drivers


```
git clone --depth=1 https://github.com/pez2001/razer_chroma_drivers.git
cd razer_blackwidow_chroma_drive
```

**Comment by terrycain** [comment]
There should be fixed, in future I shouldn't rush things :wink:

**Comment by claell** [comment]
Corrected but now there is two times cd :smiley: :

`cd cd razer_chroma_drivers`

**Comment by terrycain** [comment]
Haha, one day it will be perfect. There fixed :wink:

**Comment by claell** [comment]
Thanks ;)
