### ISSUE TITLE
Static mode doesn't work 

### ISSUE THREAD

**Issue by nicafyl** [pez2001/razer_chroma_drivers#134]
I have a Razor Ultimate 2016. Breathe, wave, starlight and probably others work fine. But, static just turns off the backlight. Using Mint 17.

**Comment by terrycain** [comment]
What command you using for static? No longer have a 2016 to play with but I'll look at the driver tomorrow

**Comment by nicafyl** [comment]
echo -n "1" >mode_static.

**Comment by terrycain** [comment]
Try
```
echo -n -e '\x00\xFF\x00' > mode_static
```

**Comment by nicafyl** [comment]
Worked. Perfect. Thanks.

**Comment by terrycain** [comment]
Yeah basically I think you can vary the 2nd byte to change the green shade
