### ISSUE TITLE
Profiles + effects

### ISSUE THREAD

**Issue by ghetolay** [pez2001/razer_chroma_drivers#58]
Is it possible to have effects to work with profiles ? I don't mean custom effect just the combination of the two. Let's take an example : We set a profile where all key are shade of blue and then we apply the reactive effect with a red color. 

1) Is it possible through configuration ?
2) Could it be added to the library ? (I could help)
3) Impossible because of the firmware of some other reason ?

Thks a lot for those drivers (razer should thks you too because this is the reason I bought this keyboard)

**Comment by terrycain** [comment]
Currently the only way to do this is by creating a library and utilising the effects part of the daemon. Obviously once it works in the daemon, we could add support for things like that in the app.

**Comment by pez2001** [comment]
ive just added a 'display profile' effect. so it is actually now possible  :-)

**Comment by terrycain** [comment]
Nice any examples? I'm working on adding logging to the daemon so probably wont commit for a while.

**Comment by pez2001** [comment]
using the daemon_controller:

-C 11 "test" test"
-S 2 0 -1 "~/.config/razer_chroma/profiles/test"
-A 2
-b 2

**Comment by pez2001** [comment]
im adding a parameter_changed event, so the -A 2 step is not needed in the near future
