### ISSUE TITLE
razer_bcd fails to start on Ubuntu 14.04

### ISSUE THREAD

**Issue by wolfen351** [pez2001/razer_chroma_drivers#84]
Hi Guys

The build etc was smooth, but then the dpkg -i runs it gives an error saying it cannot start the job. 

Manually running the service start also fails. 

    wolfen@wolfen-HP:/usr/share/razer_bcd$ sudo service razer_bcd start
    start: Job failed to start

Where can I look for more info?

I saw this in dpkg.log

    2016-02-14 12:43:36 status installed razer-chroma-driver:amd64 1.0.0

**Comment by terrycain** [comment]
`cat /var/log/upstart/razer_bcd.log` I think.

**Comment by wolfen351** [comment]
wolfen@wolfen-HP:~$ sudo cat /var/log/upstart/razer_bcd.log
    [sudo] password for wolfen: 
    Unbinding device (0003:1532:011A.0006) from hid-generic
    Binding device (0003:1532:011A.0006) to razerkbd
   /proc/self/fd/9: 20: /proc/self/fd/9: cannot create /sys/bus/hid/drivers/razerkbd/bind: Directory nonexistent
    ls: cannot access /sys/bus/hid/drivers/razerkbd/: No such file or directory
    ls: cannot access /sys/bus/hid/drivers/razermouse/: No such file or directory
    ls: cannot access /sys/bus/hid/drivers/razerfirefly/: No such file or directory

etc...

**Comment by wolfen351** [comment]
I suspect that something is missing in the install process or dependancies?

**Comment by terrycain** [comment]
Have you tried rebooting?

**Comment by wolfen351** [comment]
I will try and report back

**Comment by wolfen351** [comment]
Worked perfectly!
