### ISSUE TITLE
Razer Orbweaver Chroma support

### ISSUE THREAD

**Issue by dRaiser** [pez2001/razer_chroma_drivers#87]
Hi. I'm thinking about buying Orbweaver Chroma, is it possible that this driver would support it? Thanks!

**Comment by terrycain** [comment]
Its possible the driver could support the Orbweaver, but its doubtful the
driver will work out of the box

**Comment by terrycain** [comment]
@dRaiser are you willing to help us add support for the orbweaver?

**Comment by dRaiser** [comment]
I'm afraid not, as I don't plan of buying it until it's feature-complete on Linux.

**Comment by terrycain** [comment]
Ok, there is nothing I can do until either I get hold of an Orbweaver or unless Razer give me some technical docs for it.

**Comment by dRaiser** [comment]
I understand. If I were to buy it primary for Windows usage, I'd be happy to help, but in that case we need to wait for another enthusiast.

**Comment by terrycain** [comment]
Yeah. I'm currently in negotiations with Razer for information so I might
get some info to make an orbweaver driver. Who knows.
