### ISSUE TITLE
Set up default effect 

### ISSUE THREAD

**Issue by PychoPc** [pez2001/razer_chroma_drivers#95]
How to set up a default effect for after login?

**Comment by lah7** [comment]
There's a new option in the Chroma GUI Configuration tool. Under the spanner (top-right), there is a check box to enable (then set) startup settings.

These settings apply assuming the tray applet starts automatically at login.

**Comment by PychoPc** [comment]
Yeah. That was exactly what I was looking for.
Thank you so much for the driver

**Comment by lah7** [comment]
Oh I didn't make the driver, credit goes to @pez2001 and @terrycain as main contributors. I focus on the GUI stuff. :smile:

**Comment by PychoPc** [comment]
Okay. Thanks to the whole team

**Comment by terrycain** [comment]
:+1:
